name: Create Repository from g8 template

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "repo name"
        required: true
      organization:
        type: string
        description: "organization name"
        required: true
      package1:
        type: string
        description: "package name"
        required: true
      package2:
        type: string
        description: "package name"
        required: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create_repo:
    runs-on: ubuntu-latest
    name: create-repo
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6

      - name: current directory
        run: ls "${{ github.workspace }}"

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: create project
        run: |
          sbt 'new scala/scala-seed.g8'

       - name: show files
        run: ls "${{ github.workspace }}"
