name: Create Repository from g8 template

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "repo name"
        required: false
      organization:
        type: string
        description: "organization name"
        required: false
      package1:
        type: string
        description: "package name"
        required: false
      package2:
        type: string
        description: "package name"
        required: false

permissions:
  contents: "read"
  id-token: "write"
  actions: write

jobs:
  create_repo:
    runs-on: ubuntu-latest
    name: create-repo
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1

      - name: install g8
        run: cs install giter8

      - name: current directory
        run: ls "${{ github.workspace }}"

      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'yzhang27'
          repository: 'test-workflow'
          access-token: ${{ secrets.AUTH_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: create project
        run: |
          g8 https://github.com/yzhang27/test-g8.g8 --name=test-g8 --package1=test-package1 --package2=test-package2 -o test-workflow

      - name: show files
        run: |
          ls "${{ github.workspace }}"
          cd test-workflow
          ls

      - name: push files
        run: |
          cd test-workflow
          ls
          git add .
          git commit -m 'add files generated from g8'
          git push
