name: Create Repository from g8 template

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "repo name"
        required: true
      organization:
        type: string
        description: "organization name"
        required: true
      package1:
        type: string
        description: "package name"
        required: true
      package2:
        type: string
        description: "package name"
        required: true

permissions:
  contents: "read"
  id-token: "write"
  actions: write

jobs:
  create_repo:
    runs-on: ubuntu-latest
    name: create-repo
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1

      - name: install g8
        run: cs install giter8

      - name: current directory
        run: ls "${{ github.workspace }}"

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: create project
        run: |
          g8 https://github.com/yzhang27/test-g8.g8 --name=${{ inputs.name }} --package1=${{ inputs.package1 }} --package2=${{ inputs.package2 }}

      - name: show files
        run: |
          ls "${{ github.workspace }}"
          cd ${{ inputs.name }}
          ls
