name: Create Repository from g8 template

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "repo name"
        required: true
      organization:
        type: string
        description: "organization name"
        required: true
      package1:
        type: string
        description: "package name"
        required: true
      package2:
        type: string
        description: "package name"
        required: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  create_repo:
    runs-on: ubuntu-latest
    name: create-repo
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1

      - name: install g8
        run: cs install giter8

      - name: current directory
        run: ls "${{ github.workspace }}"

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: create project
        run: |
          g8 unfiltered/unfiltered.g8 --name=name --version=0.1.0-SNAPSHOT --scala_version=scala_version --sbt_version=sbt_version  --unfiltered_version=unfiltered_version  --description=description

      - name: show files
        run: ls "${{ github.workspace }}"
